Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -4,8 +4,14 @@ pipeline {
   stages {
     stage('Init Project') {
       steps {
-      sh 'npm --version'
-        echo "NPM INIT"
+      # Node Version Manager with Jenkins
+      # https://github.com/creationix/nvm , https://www.sitepoint.com/quick-tip-multiple-versions-node-nvm/
+      set +ex                     # immediate script fail off, echo off
+      export NVM_DIR="$HOME/.nvm" # set local path to NVM
+      . ~/.nvm/nvm.sh             # add NVM into the Shell session
+      nvm install v6.9.1          # first time only
+      nvm use v6.9.1              # choose current version
+      set -ex 
       }
     }
        
